### ISSUE TITLE
Are we 1.0 yet?

### ISSUE THREAD

**Issue by superlukas** [suitcss/base#21]
I just saw #20 and thought backwards-compatibility would be a nice thing to have.

**Comment by superlukas** [comment]
Another question I have is about the two normalizations in base.css. Why are they here and not in normalize.css?

/cc @necolas

**Comment by giuseppeg** [comment]
@simonsmith before tagging v1 maybe we can replace "links" with "elements" [here](https://github.com/suitcss/base/blob/master/lib/base.css#L56)

**Comment by simonsmith** [comment]
Done in https://github.com/suitcss/base/commit/935fdbac3c15fb0a77772cc4dd1baf8fbc69611e

**Comment by simonsmith** [comment]
Released 1.0 - https://github.com/suitcss/base/releases/tag/1.0.0
