### ISSUE TITLE
Wrong comment on box-sizing: border-box

### ISSUE THREAD

**Issue by greengiraffe** [suitcss/base#33]
[In `base.css`](https://github.com/suitcss/base/blob/master/lib/base.css#L7) it says:

> Prevent margin and border from affecting element width.

This is wrong. It should say:

>  Prevent **padding** and border from affecting element width.

Ref: https://developer.mozilla.org/en/docs/Web/CSS/box-sizing

Furthermore I'd prefer a non-minified link to the CSS-Tricks page, but that's just my two cents. ;)

**Comment by simonsmith** [comment]
Good catch, I'll update that comment. And the short URL keeps the text within 80 characters which is picked up by Stylelint.

**Comment by simonsmith** [comment]
Fixed in latest release
