### ISSUE TITLE
Would you like to add a rule to reset <form>?

### ISSUE THREAD

**Issue by morishitter** [suitcss/base#34]
like this:

```
form {
  margin: 0;
}
```

**Comment by giuseppeg** [comment]
hi @morishitter, yes. Actually I would like to add a rule to reset all of the margins
```css
* { margin: 0 }
```

**Comment by giuseppeg** [comment]
@morishitter out of curiosity why do you need to reset the `form`'s margin? 
This specific element doesn't seem to have *default* margins.

**Comment by simonsmith** [comment]
> I would like to add a rule to reset all of the margins

Are we missing any?

**Comment by giuseppeg** [comment]
In fact they are probably all there.
@morishitter can we close this issue?

**Comment by morishitter** [comment]
@giuseppeg Sorry I'm late. Thanks :)
