### ISSUE TITLE
Duplication of rules

### ISSUE THREAD

**Issue by racse1** [suitcss/base#39]
Hi there,

I noticed that the latest release has two `fieldset` rules in `lib/base.scss`:

* https://github.com/suitcss/base/blob/master/lib/base.css#L59-L63
* https://github.com/suitcss/base/blob/master/lib/base.css#L114-L118

I don't know which one is correct, but it seems like setting some actual styling on `fieldset` should be on normalize.css' shoulders.

Any thoughts?

Thanks!

**Comment by racse1** [comment]
I guess, it's sort of related https://github.com/necolas/normalize.css/blob/master/normalize.css#L311-L313.

**Comment by simonsmith** [comment]
Good catch. Looks like a leftover from when a bunch of defaults were taken out of normalize in `6.0.0`. Seeing as it's all been reverted in `7.0.0` we can remove all those rules again.

**Comment by simonsmith** [comment]
Fixed in `4.0.0`
